Creating a nested list to act as the Sudoko game board.

In [14]:
import numpy as np
import tkinter as tk
board=[[2,0,0,0,0,3,0,7,0],
       [0,0,7,0,0,5,8,0,3],
       [5,0,0,0,7,4,0,2,6],
       [0,0,0,0,8,0,3,0,7],
       [0,7,0,0,0,0,0,1,0],
       [9,0,5,0,1,0,0,0,0],
       [7,5,0,4,3,0,0,0,1],
       [8,0,3,9,0,0,7,0,0],
       [0,1,0,7,0,0,0,0,8]]
grid=np.array(board)
print(grid)

[[2 0 0 0 0 3 0 7 0]
 [0 0 7 0 0 5 8 0 3]
 [5 0 0 0 7 4 0 2 6]
 [0 0 0 0 8 0 3 0 7]
 [0 7 0 0 0 0 0 1 0]
 [9 0 5 0 1 0 0 0 0]
 [7 5 0 4 3 0 0 0 1]
 [8 0 3 9 0 0 7 0 0]
 [0 1 0 7 0 0 0 0 8]]


Define a function that can check if a tested value n works with the filled out board.

In [15]:
def checker(d,a,n):
    global grid
    if n in grid[:,a]:
        return False
    elif n in grid[d,:]:
        return False
    a0=(a//3)*3
    d0=(d//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[d0+i][a0+j]==n:
                return False
    return True

Define a function that can loop through the cells and test numbers 1-9 in cells with the value 0. If the value is possible update the grid and run the solver function again(recursion).

In [16]:
def solver():
    check=[]
    for d in range(9):
        for a in range(9):
            if grid[d][a]==0:
                for n in range(1,10):
                    if checker(d,a,n):
                        grid[d][a]=n
                        solver()
                        grid[d][a] = 0
                return
    print(np.matrix(grid))

Test the program.

In [17]:
solver()

[[2 8 4 6 9 3 1 7 5]
 [6 9 7 1 2 5 8 4 3]
 [5 3 1 8 7 4 9 2 6]
 [1 4 2 5 8 9 3 6 7]
 [3 7 8 2 4 6 5 1 9]
 [9 6 5 3 1 7 4 8 2]
 [7 5 6 4 3 8 2 9 1]
 [8 2 3 9 6 1 7 5 4]
 [4 1 9 7 5 2 6 3 8]]


In [18]:
grid

array([[2, 0, 0, 0, 0, 3, 0, 7, 0],
       [0, 0, 7, 0, 0, 5, 8, 0, 3],
       [5, 0, 0, 0, 7, 4, 0, 2, 6],
       [0, 0, 0, 0, 8, 0, 3, 0, 7],
       [0, 7, 0, 0, 0, 0, 0, 1, 0],
       [9, 0, 5, 0, 1, 0, 0, 0, 0],
       [7, 5, 0, 4, 3, 0, 0, 0, 1],
       [8, 0, 3, 9, 0, 0, 7, 0, 0],
       [0, 1, 0, 7, 0, 0, 0, 0, 8]])